name: 'docker-remix'

services:
  remix:
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 5173:5173
    command:
      - npm
      - run
      - dev
